server:
   port: 9001
spring:
   application:
      name: eureka-server
eureka:
   instance:
      hostname: localhost
      lease-renewal-interval-in-seconds: 30
   server:
      enable-self-preservation: true # 自我保护模式关闭
      renewal-percent-threshold: 0.49
   client:
      register-with-eureka: false # 作为注册中心服务，不向自己注册自己
      fetch-registry: false # 注册中心负责维护服务实例，不做检索服务
      service-url:
         defaultZone: http://localhost:9002/eureaka/ # ,http://eureak3:9003/eurka/