server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    region: eureka # 设置region 地域
    availability-zones: # 设置zones 可用区
      eureka: defaultZone
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # defaultZone: http://${user.username}:${user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#      zone: http://${eureka.instance.hostname}:${server.port}/eureka/












