spring:
  application:
    name: api-getway
server:  port: 5555
zuul:  routes:
    api-a:
      path: /api-a/**
      service-id: panda-frame
    api-b:
      path: /api-b/**
      service-id: feign-consumer
eureka:  client:    service-url:      defaultZone: http://eureak1:9001/eureka/