
mybatis-plus:
  check-config-location: true
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: ""
  configuration:
    default-executor-type: simple
    map-underscore-to-camel-case: true
    cache-enabled: true
    aggressive-lazy-loading: true
    auto-mapping-unknown-column-behavior: warning
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: false # 映射结果多个数据集
  global-config:
    db-config:
      table-underline: true # 表名下划线默认true
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: 0
      capital-mode: false
      logic-not-delete-value: 0
      logic-delete-value: 1
      table-prefix: lea
      column-format: true
      insert-strategy: not_empty
      update-strategy: not_empty
#      logic-delete-field:

# mysql 配置
spring:
  datasource:
    username: root
    password: 0205.leablogs.com
    url: jdbc:mysql://leablogs.com:13307/sys?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: select 1 from DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;durid.stat.slowQulMills=5000
      filters: stat,wall,log4j,config
      filter:
        stat:
          slow-sql-millis: 30000
          log-slow-sql: true
          db-type: mysql
        log4j:
          connection-close-after-log-enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: druid
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: admin
#        allow:
#        deny:
server:
  port: 8081



























