server:  port: 4001
spring:
  application:
    name: rabbitmq
  rabbitmq:    host: 192.168.80.131
    port: 5672
    username: guest
    password: guest    cache:      channel:        size: 50        mq:  defaultExchange: amqpExchange  queue: queue  routeKey: queue_key