server:
  port: 6002
eureka:
  server:
    port: 9001
    address: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.address}:${eureka.server.port}/eureka/
  instance:
    instance-id: ${eureka.server.address}:${server.port}
    prefer-ip-address: true
    status-page-url-path: /index.html
    status-page-url: http://${eureka.server.address}:${eureka.server.port}/info
#    health-check-url: 
#    home-page-url: 
#    home-page-url-path: 
spring:
#  cloud:
#    inetutils:
#      default-ip-address: 192.168.0.105
  application:
    name: panda-client