spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    enabled: true
    servlet:
      content-type: text/html; charset=utf-8
    prefix: classpath:/templates/
server:
  port: 8081
#logging:
#  config: classpath:log4j.properties